### ISSUE TITLE
Can't ask someone to become part of secret cult (or i don't understand the game mechanic)

### ISSUE THREAD

**Issue by Adminusart** [ck2plus/CleanSlate#124]
I was playing as a catholic ruler and adopted secretly Fraticielli (toghether with my bishop) . I tried finiding the character interaction to try to make people join my secret cult but it wasnt there, nor on my children,  nor my wife. I may not understand how this mechanic works tho. If so sorry for the issue spam.

**Comment by SuccinctScrivener** [comment]
Were you also a part of a secret cult? Having a secret religion by itself does not imply that you are in a secret cult. In order to recruit people to your secret religion, you would have to found a cult in the intrigue decisions menu if nobody's created one for your secret religion yet, or join the cult in society menu if somebody has.

**Comment by Adminusart** [comment]
yup yup i founded the secret cult, and added my bishop, i could do the prepare ground decision (from the province view) but couldnt acces the interaction to try to add somebody to it who isnt secretly fraticcielli already like my bishop.
