### ISSUE TITLE
Proposal: Dummy achievements.txt in exchange of performance

### ISSUE THREAD

**Issue by Aerotinge** [ck2plus/CleanSlate#132]
common/achievements.txt stores triggers of Steam Achievements, which is not possible to fire with a mod like CleanSlate
However it still processed by the game engine and takes CPU times.
By emptying this file, the game can run ~6%* faster. It's a very cheap and easy way to gain performance with no risks of touching other content files.

*1.059 faster, bm 1066.9.15 start, total_years_played == 5, observation
**it might vary on devices

**Comment by SuccinctScrivener** [comment]
I have had similar thoughts. I would probably comment out the events rather than just omitting them entirely. And the event `steam.026` is actually used for non-achievement reasons. If we were doing this, we could also comment out all of the achievement flag setting sections throughout the rest of the code, though I imagine the performance gains from doing that would relatively minimal.

**Comment by Aerotinge** [comment]
I prefer not to touch /events at all. Too many efforts for very little performance. You know.
Dummy a single achievements.txt is the simplest way to save performance I could imagine.

It's still provide a chance for those who want to play Ironman with CleanSlate under a patched CK2. Just throwing back this file and the achievement works again.

**Comment by SuccinctScrivener** [comment]
Good point, I hadn't considered people using workarounds to re-enable achievements. I still think it might be worthwhile to comment out base_achievement_events.txt (and its on_action file) in addition to achievements.txt, given the number of events there, especially MTTH ones. But yeah doing anything else outside those files is probably too much effort.

**Comment by Whizzer** [comment]
I doubt there would be a measurable performance difference at all, but if there is, we could indeed go down that route.

**Comment by Zsar** [comment]
Note that with the mod [Modded Achievment Patcher](https://steamcommunity.com/sharedfiles/filedetails/?id=3450790947) it ought to be possible to earn achievements with Clean Slate (and for Clean Slate to _fix/improve_ achievements with questionable triggers or descriptions).

As Clean Slate is de facto the unofficial patch mod for CK2 and _specifically_ unlocks some vanilla content unreachable due to broken triggers, I think it is by now unreasonable to play CK2 without Clean Slate and thence it would be very fine if Clean Slate would support achievement hunting.

**Comment by schwarherz** [comment]
Yeah, unless someone changed it since this was discussed (three years ago) the achievement events should still be properly in-place in CleanSlate for exactly this type of reason.
